networks:
  horn:
    ipam:
      driver: default
      config:
        - subnet: 172.60.0.0/24

x-local-dev-volumes: &local-dev-volumes
  - type: bind
    source: ../public/
    target: /home/anvil/public/
    bind:
      create_host_path: false
  - type: bind
    source: ../src/
    target: /home/anvil/src/
    bind:
      create_host_path: false
  - type: bind
    source: ../assets/
    target: /home/anvil/assets/
    bind:
      create_host_path: false
  - type: bind
    source: ../tests/
    target: /home/anvil/tests/
    bind:
      create_host_path: false
  - type: bind
    source: ../package.json
    target: /home/anvil/package.json
    bind:
      create_host_path: false
  - type: bind
    source: ../elm.json
    target: /home/anvil/elm.json
    bind:
      create_host_path: false
  - type: bind
    source: ../elm-package.json
    target: /home/anvil/elm-package.json
    bind:
      create_host_path: false

services:
  dev:
    build:
      context: ..
      target: dev
      dockerfile: .docker/Dockerfile
    environment:
      LUPUSMICHAELIS_DEV_USER_ALIAS:
      LUPUSMICHAELIS_DEV_UID:
      LUPUSMICHAELIS_DEV_GID:
    restart: unless-stopped
    networks:
      horn:
        ipv4_address: 172.60.0.110
    volumes:
      *local-dev-volumes

  test:
    build:
      context: ..
      target: dev
      dockerfile: .docker/Dockerfile
    command: [ "npm", "run", "test" ]
    environment:
      LUPUSMICHAELIS_DEV_USER_ALIAS:
      LUPUSMICHAELIS_DEV_UID:
      LUPUSMICHAELIS_DEV_GID:
    restart: unless-stopped
    volumes:
      *local-dev-volumes

  live:
    build:
      context: ..
      target: secure-static
      dockerfile: .docker/Dockerfile
    restart: no
    networks:
      horn:
        ipv4_address: 172.60.0.100
